-- ParkPilot: (removed) demo catalogue.
--
-- This migration used to insert eight Toronto parking listings with fixed ids
-- `11111111-1111-4111-8111-1111111111XX`. They were never real spaces — they
-- existed so the driver experience matched the design before any host had
-- listed anything.
--
-- The rows were deleted by `0021_remove_demo_catalogue.sql`, and the insert is
-- removed here as well so that rebuilding the database from scratch cannot
-- bring them back.
--
-- Intentionally empty.
