-- ParkPilot: (removed) free demo listing.
--
-- This migration used to insert a $0.00 "Free Test Spot (Demo)" at
-- `11111111-1111-4111-8111-111111111110`, so the reserve -> pass flow could be
-- exercised without an on-chain payment.
--
-- The row was deleted by `0021_remove_demo_catalogue.sql`, and the insert is
-- removed here so a rebuild cannot bring it back.
--
-- The behaviour it relied on is still supported and unchanged: `price_usdt = 0`
-- is allowed by the schema, and the backend treats a zero total as a free
-- reservation that is confirmed immediately with no payment or ledger rows. A
-- host can create one through the normal flow if it is ever needed again.
--
-- Intentionally empty.
