-- ParkPilot: (removed) demo catalogue restore.
--
-- This migration re-inserted the demo listings after some of them were deleted
-- during host-UI testing. It is the clearest example of why the demo data had
-- to go: deleting the rows was never enough while a migration could put them
-- back.
--
-- The rows were deleted by `0021_remove_demo_catalogue.sql`, and the insert is
-- removed here so a rebuild cannot bring them back.
--
-- Intentionally empty.
